name: Mirror

on:
  push:
  repository_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  apt-mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Client
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com
        repository: stardustdl/apt-mirror-http-server
        tags: latest
        dockerfile: ./apt-mirror/Dockerfile
  judge0:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Client
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com
        repository: stardustdl/judge0
        tags: "1.9.0"
        dockerfile: ./judge0/Dockerfile
  gitea:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Client
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com
        repository: stardustdl/gitea
        tags: latest
        dockerfile: ./gitea/Dockerfile
  minio:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Client
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com
        repository: stardustdl/minio
        tags: latest
        dockerfile: ./minio/Dockerfile